# Generated by Django 3.1 on 2024-07-10 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('phone', models.CharField(blank=True, max_length=350, null=True, verbose_name='Celular')),
                ('profession', models.CharField(blank=True, max_length=350, null=True, verbose_name='Profesion')),
                ('email', models.CharField(blank=True, max_length=350, null=True, verbose_name='Correo')),
                ('workplace', models.CharField(blank=True, max_length=350, null=True, verbose_name='Lugar de trabajo')),
                ('phone_number_work', models.CharField(blank=True, max_length=350, null=True, verbose_name='Telefono de trabajo')),
                ('monthly_income', models.CharField(blank=True, max_length=350, null=True, verbose_name='Ingresos Mensuales')),
                ('type_of_housing', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Propia'), (1, 'Arrendada'), (2, 'Otra')], null=True, verbose_name='Tipo de Usuario')),
                ('vehicle', models.BooleanField(default=False, verbose_name='Tiene vehiculo?')),
                ('it_financial', models.BooleanField(default=False, verbose_name='Es acudiente financiero?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('civil_registration', models.FileField(blank=True, null=True, upload_to='civil_registration/', verbose_name='Registro civil')),
                ('vaccination_card', models.FileField(upload_to='vaccination_card/', verbose_name='Carnet vacunas')),
                ('identity_card', models.FileField(upload_to='identity_card', verbose_name='Tarjeta identidad')),
                ('last_newsletter', models.FileField(upload_to='last_newsletter/', verbose_name='Ultimo boletin')),
                ('work_record', models.FileField(upload_to='work_record', verbose_name='Constancia laboral Acudiente')),
                ('photo_license', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto perfil')),
                ('registration_receipt', models.ImageField(upload_to='registration_receipt/', verbose_name='Recibo pago de inscripcion')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.candidate', verbose_name='Candidato')),
                ('tutors', models.ManyToManyField(blank=True, null=True, related_name='inscription_tutor', to='tutor.Tutor', verbose_name='Tutor/es')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-id'],
            },
        ),
    ]
