# Generated by Django 3.1 on 2024-08-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='vehicle',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tiene vehiculo?'),
        ),
    ]
