# Generated by Django 3.1 on 2024-08-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20240814_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='it_financial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es acudiente financiero?'),
        ),
    ]
