version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres_web
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    environment:
      POSTGRES_DB: web_db_pnd6
      POSTGRES_USER: web_user
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: 66up9x2JFb71tdpNYz2RTEPsHCpLLC55
      PGDATA: /tmp

  redis:
    image: bitnami/redis:latest
    container_name: redis_web
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: ABCDE

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
