# Generated by Django 3.1 on 2024-04-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(blank=True, max_length=340, null=True, verbose_name='Codigo')),
                ('name', models.CharField(blank=True, max_length=340, null=True, verbose_name='Nombre')),
                ('degress', models.PositiveSmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Septimo'), (8, 'Octavo'), (9, 'Noveno'), (10, 'Decimo'), (11, 'Once')], help_text='Grado educativo', verbose_name='Grado')),
                ('teachers', models.ManyToManyField(blank=True, related_name='academic_teachers', to='teacher.Teacher', verbose_name='Profesor(es)')),
            ],
            options={
                'verbose_name': 'Grado Academico',
                'verbose_name_plural': 'Grados Academicos',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha registro')),
                ('academic_groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollments.academicgroups', verbose_name='Grupos Academicos')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('subjects', models.ManyToManyField(blank=True, related_name='enrollment_subjects', to='teacher.Subject', verbose_name='Asignatura(s)')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'ordering': ['id'],
            },
        ),
    ]
