# Generated by Django 3.1 on 2024-07-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroups',
            options={'verbose_name': 'Grupos Academico', 'verbose_name_plural': 'Grupos Academicos'},
        ),
    ]
