# Generated by Django 3.1 on 2023-10-27 11:18

from django.db import migrations, models
import imagekit.models.fields
import web.apps.users.files


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web.apps.users.files.user_avatar_image_path, verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Url foto de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Administrador'), (1, 'Rector'), (2, 'Director'), (3, 'Jefe de sistemas'), (4, 'Docente'), (5, 'Estudiante'), (6, 'Acudiente'), (7, 'Otro'), (8, 'Coordinador')], help_text='Administración / Cliente', verbose_name='Tipo de Usuario'),
        ),
    ]
