# Generated by Django 3.1 on 2024-04-11 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231027_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(12)], verbose_name='Numero de Documento'),
        ),
    ]
