# Generated by Django 3.1 on 2024-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_document',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cedula de Ciudadania'), (1, 'Tarjeta de Identidad'), (2, 'Pasaporte'), (3, 'Otro')], help_text='Escoja su tipo de identificacions', null=True, verbose_name='Tipo de Identificacion'),
        ),
    ]
