# Generated by Django 3.1 on 2024-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Documento'),
        ),
    ]
