# Generated by Django 3.1 on 2024-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.CharField(blank=True, max_length=340, null=True, verbose_name='Profecion'),
        ),
    ]
